// 2026-10-08 20:46 KST

const QUESTIONS = [
  // ===== 한국사 =====
  {
    category: "한국사",
    question: "1443년 훈민정음을 창제하고 1446년에 반포한 조선의 왕은?",
    choices: ["태종", "세종", "세조", "성종"],
    answer: 1,
    explanation: "세종은 1443년 겨울 훈민정음을 창제했고, 1446년 9월 상순에 반포했다.",
    source: { title: "한국민족문화대백과사전, 훈민정음", url: "https://encykorea.aks.ac.kr/Article/E0065805" },
  },
  {
    category: "한국사",
    question: "918년 고려를 세운 인물은?",
    choices: ["궁예", "견훤", "왕건", "이성계"],
    answer: 2,
    explanation: "고려는 918년 개성 출신 왕건이 세웠고, 936년 후삼국을 통합했다.",
    source: { title: "한국민족문화대백과사전, 고려", url: "https://encykorea.aks.ac.kr/Article/E0003424" },
  },
  {
    category: "한국사",
    question: "몽골의 침입을 불력으로 물리치려는 염원으로 새긴 고려 대장경판(팔만대장경판)을 보관하고 있는 사찰은?",
    choices: ["해인사", "불국사", "송광사", "통도사"],
    answer: 0,
    explanation: "팔만대장경판은 몽골 침입 때 새긴 것으로, 지금 합천 해인사에 보관되어 있다.",
    source: { title: "한국민족문화대백과사전, 합천 해인사 대장경판", url: "https://encykorea.aks.ac.kr/Article/E0062711" },
  },
  {
    category: "한국사",
    question: "1592년 한산섬 앞바다에서 학익진으로 일본 수군을 크게 무찌른 조선 수군의 지휘관은?",
    choices: ["권율", "김시민", "곽재우", "이순신"],
    answer: 3,
    explanation: "한산도대첩에서 전라좌수사 이순신은 모든 전선이 학익진을 짜서 공격하게 했다.",
    source: { title: "한국민족문화대백과사전, 한산도대첩", url: "https://encykorea.aks.ac.kr/Article/E0061676" },
  },
  {
    category: "한국사",
    question: "1919년 4월 11일 대한민국임시정부가 수립된 도시는?",
    choices: ["상하이", "충칭", "베이징", "도쿄"],
    answer: 0,
    explanation: "대한민국임시정부는 3·1운동 이후인 1919년 4월 11일 중국 상하이에서 수립되었다.",
    source: { title: "한국민족문화대백과사전, 대한민국 임시정부 수립 기념일", url: "https://encykorea.aks.ac.kr/Article/E0080590" },
  },
  {
    category: "한국사",
    question: "1894년 동학농민군을 이끌고 봉기했으며, 몸집이 작아 '녹두장군'이라 불린 인물은?",
    choices: ["최제우", "전봉준", "김옥균", "홍경래"],
    answer: 1,
    explanation: "전봉준은 몸이 왜소해 녹두라 불렸고, 1894년 동학농민군을 이끌고 봉기했다.",
    source: { title: "한국민족문화대백과사전, 전봉준", url: "https://encykorea.aks.ac.kr/Article/E0049437" },
  },
  {
    category: "한국사",
    question: "1377년 청주 흥덕사에서 금속활자로 인쇄한 책은?",
    choices: ["삼국유사", "동의보감", "불조직지심체요절", "용비어천가"],
    answer: 2,
    explanation: "직지는 1377년 흥덕사에서 금속활자로 찍었고, 2001년 유네스코 세계기록유산에 올랐다.",
    source: { title: "한국민족문화대백과사전, 불조직지심체요절", url: "https://encykorea.aks.ac.kr/Article/E0025035" },
  },
  {
    category: "한국사",
    question: "1861년 목판본으로 제작된 전국 지도첩 '대동여지도'를 만든 인물은?",
    choices: ["정약용", "정상기", "박지원", "김정호"],
    answer: 3,
    explanation: "대동여지도는 1861년 김정호가 목판본으로 제작한 절첩분첩식 전국 지도첩이다.",
    source: { title: "한국민족문화대백과사전, 대동여지도", url: "https://encykorea.aks.ac.kr/Article/E0014266" },
  },
  {
    category: "한국사",
    question: "6·25 전쟁(한국전쟁)의 휴전협정이 이루어진 해는?",
    choices: ["1950년", "1951년", "1953년", "1955년"],
    answer: 2,
    explanation: "1953년 7월 27일 휴전협정이 이루어져 3년 1개월에 걸친 전쟁이 중지되었다.",
    source: { title: "한국민족문화대백과사전, 한국전쟁", url: "https://encykorea.aks.ac.kr/Article/E0042143" },
  },
  {
    category: "한국사",
    question: "828년 완도에 청해진을 건설하고 남해의 해상권을 장악한 신라의 인물은?",
    choices: ["장보고", "김유신", "최치원", "원효"],
    answer: 0,
    explanation: "장보고는 828년 완도에 청해진을 건설해 당, 신라, 일본을 잇는 무역을 주도했다.",
    source: { title: "한국민족문화대백과사전, 장보고", url: "https://encykorea.aks.ac.kr/Article/E0048474" },
  },

  // ===== 세계지리 =====
  {
    category: "세계지리",
    question: "오스트레일리아의 수도는?",
    choices: ["시드니", "멜버른", "캔버라", "퍼스"],
    answer: 2,
    explanation: "캔버라는 오스트레일리아 연방의 수도로, 시드니에서 남서쪽으로 약 240km 떨어져 있다.",
    source: { title: "Britannica, Canberra", url: "https://www.britannica.com/place/Canberra" },
  },
  {
    category: "세계지리",
    question: "나일강이 북쪽으로 흘러 마지막에 흘러드는 바다는?",
    choices: ["홍해", "지중해", "아라비아해", "흑해"],
    answer: 1,
    explanation: "나일강은 적도 남쪽에서 시작해 아프리카 북동부를 지나 지중해로 흘러든다.",
    source: { title: "Britannica, Nile River", url: "https://www.britannica.com/place/Nile-River" },
  },
  {
    category: "세계지리",
    question: "안데스산맥이 있는 대륙은?",
    choices: ["남아메리카", "아프리카", "아시아", "북아메리카"],
    answer: 0,
    explanation: "안데스산맥은 남아메리카의 산계로, 대륙 남쪽 끝에서 카리브해 연안까지 이어진다.",
    source: { title: "Britannica, Andes Mountains", url: "https://www.britannica.com/place/Andes-Mountains" },
  },
  {
    category: "세계지리",
    question: "아프리카 북부의 거의 전체를 차지하는 사막은?",
    choices: ["고비 사막", "아타카마 사막", "칼라하리 사막", "사하라 사막"],
    answer: 3,
    explanation: "사하라 사막은 아프리카 북부의 거의 전체를 차지하며, 동서 길이가 약 4,800km이다.",
    source: { title: "Britannica, Sahara", url: "https://www.britannica.com/place/Sahara-desert-Africa" },
  },
  {
    category: "세계지리",
    question: "튀르키예(터키)의 수도는?",
    choices: ["이스탄불", "앙카라", "이즈미르", "안탈리아"],
    answer: 1,
    explanation: "앙카라는 튀르키예의 수도로, 나라의 북서부에 있다.",
    source: { title: "Britannica, Ankara", url: "https://www.britannica.com/place/Ankara" },
  },
  {
    category: "세계지리",
    question: "킬리만자로산이 있는 나라는?",
    choices: ["탄자니아", "에티오피아", "우간다", "남아프리카 공화국"],
    answer: 0,
    explanation: "킬리만자로는 탄자니아 북동부, 케냐 국경 가까이에 있는 화산 산괴이다.",
    source: { title: "Britannica, Kilimanjaro", url: "https://www.britannica.com/place/Kilimanjaro" },
  },
  {
    category: "세계지리",
    question: "아마존강이 흘러드는 대양은?",
    choices: ["태평양", "인도양", "대서양", "북극해"],
    answer: 2,
    explanation: "아마존강은 페루 안데스산맥에서 시작해 브라질을 지나 대서양으로 흘러든다.",
    source: { title: "Britannica, Amazon River", url: "https://www.britannica.com/place/Amazon-River" },
  },
  {
    category: "세계지리",
    question: "에베레스트산이 국경에 걸쳐 있는 두 나라는?",
    choices: ["인도와 네팔", "인도와 파키스탄", "부탄과 중국", "네팔과 중국"],
    answer: 3,
    explanation: "에베레스트산은 네팔과 중국 티베트 자치구의 국경에 있다.",
    source: { title: "Britannica, Mount Everest", url: "https://www.britannica.com/place/Mount-Everest" },
  },
  {
    category: "세계지리",
    question: "이집트의 수에즈 운하가 잇는 두 바다는?",
    choices: ["지중해와 홍해", "지중해와 흑해", "홍해와 아라비아해", "흑해와 카스피해"],
    answer: 0,
    explanation: "수에즈 운하는 이집트의 수에즈 지협을 남북으로 가로질러 지중해와 홍해를 잇는다.",
    source: { title: "Britannica, Suez Canal", url: "https://www.britannica.com/topic/Suez-Canal" },
  },
  {
    category: "세계지리",
    question: "브라질의 공용어는?",
    choices: ["스페인어", "포르투갈어", "영어", "프랑스어"],
    answer: 1,
    explanation: "브라질에서는 포르투갈어가 주된 언어가 되었고, 오늘날에도 공용어이다.",
    source: { title: "Britannica, Brazil", url: "https://www.britannica.com/place/Brazil" },
  },
];
if (typeof module !== "undefined") module.exports = QUESTIONS;
