// 2026-10-08 20:46 KST

const QUESTIONS = [
  // ===== 한국사 =====
  {
    category: "한국사",
    question: "1443년 훈민정음을 창제하고 1446년에 반포한 조선의 왕은?",
    choices: ["태종", "세종", "세조", "성종"],
    answer: 1,
    explanation: "세종은 1443년 겨울 훈민정음을 창제했고, 1446년 9월 상순에 반포했다.",
    source: { title: "한국민족문화대백과사전, 훈민정음", url: "https://encykorea.aks.ac.kr/Article/E0065805" },
  },
  {
    category: "한국사",
    question: "918년 고려를 세운 인물은?",
    choices: ["궁예", "견훤", "왕건", "이성계"],
    answer: 2,
    explanation: "고려는 918년 개성 출신 왕건이 세웠고, 936년 후삼국을 통합했다.",
    source: { title: "한국민족문화대백과사전, 고려", url: "https://encykorea.aks.ac.kr/Article/E0003424" },
  },
  {
    category: "한국사",
    question: "몽골의 침입을 불력으로 물리치려는 염원으로 새긴 고려 대장경판(팔만대장경판)을 보관하고 있는 사찰은?",
    choices: ["해인사", "불국사", "송광사", "통도사"],
    answer: 0,
    explanation: "팔만대장경판은 몽골 침입 때 새긴 것으로, 지금 합천 해인사에 보관되어 있다.",
    source: { title: "한국민족문화대백과사전, 합천 해인사 대장경판", url: "https://encykorea.aks.ac.kr/Article/E0062711" },
  },
  {
    category: "한국사",
    question: "1592년 한산섬 앞바다에서 학익진으로 일본 수군을 크게 무찌른 조선 수군의 지휘관은?",
    choices: ["권율", "김시민", "곽재우", "이순신"],
    answer: 3,
    explanation: "한산도대첩에서 전라좌수사 이순신은 모든 전선이 학익진을 짜서 공격하게 했다.",
    source: { title: "한국민족문화대백과사전, 한산도대첩", url: "https://encykorea.aks.ac.kr/Article/E0061676" },
  },
  {
    category: "한국사",
    question: "1919년 4월 11일 대한민국임시정부가 수립된 도시는?",
    choices: ["상하이", "충칭", "베이징", "도쿄"],
    answer: 0,
    explanation: "대한민국임시정부는 3·1운동 이후인 1919년 4월 11일 중국 상하이에서 수립되었다.",
    source: { title: "한국민족문화대백과사전, 대한민국 임시정부 수립 기념일", url: "https://encykorea.aks.ac.kr/Article/E0080590" },
  },
  {
    category: "한국사",
    question: "1894년 동학농민군을 이끌고 봉기했으며, 몸집이 작아 '녹두장군'이라 불린 인물은?",
    choices: ["최제우", "전봉준", "김옥균", "홍경래"],
    answer: 1,
    explanation: "전봉준은 몸이 왜소해 녹두라 불렸고, 1894년 동학농민군을 이끌고 봉기했다.",
    source: { title: "한국민족문화대백과사전, 전봉준", url: "https://encykorea.aks.ac.kr/Article/E0049437" },
  },
  {
    category: "한국사",
    question: "1377년 청주 흥덕사에서 금속활자로 인쇄한 책은?",
    choices: ["삼국유사", "동의보감", "불조직지심체요절", "용비어천가"],
    answer: 2,
    explanation: "직지는 1377년 흥덕사에서 금속활자로 찍었고, 2001년 유네스코 세계기록유산에 올랐다.",
    source: { title: "한국민족문화대백과사전, 불조직지심체요절", url: "https://encykorea.aks.ac.kr/Article/E0025035" },
  },
  {
    category: "한국사",
    question: "1861년 목판본으로 제작된 전국 지도첩 '대동여지도'를 만든 인물은?",
    choices: ["정약용", "정상기", "박지원", "김정호"],
    answer: 3,
    explanation: "대동여지도는 1861년 김정호가 목판본으로 제작한 절첩분첩식 전국 지도첩이다.",
    source: { title: "한국민족문화대백과사전, 대동여지도", url: "https://encykorea.aks.ac.kr/Article/E0014266" },
  },
  {
    category: "한국사",
    question: "6·25 전쟁(한국전쟁)의 휴전협정이 이루어진 해는?",
    choices: ["1950년", "1951년", "1953년", "1955년"],
    answer: 2,
    explanation: "1953년 7월 27일 휴전협정이 이루어져 3년 1개월에 걸친 전쟁이 중지되었다.",
    source: { title: "한국민족문화대백과사전, 한국전쟁", url: "https://encykorea.aks.ac.kr/Article/E0042143" },
  },
  {
    category: "한국사",
    question: "828년 완도에 청해진을 건설하고 남해의 해상권을 장악한 신라의 인물은?",
    choices: ["장보고", "김유신", "최치원", "원효"],
    answer: 0,
    explanation: "장보고는 828년 완도에 청해진을 건설해 당, 신라, 일본을 잇는 무역을 주도했다.",
    source: { title: "한국민족문화대백과사전, 장보고", url: "https://encykorea.aks.ac.kr/Article/E0048474" },
  },

  // ===== 세계지리 =====
  {
    category: "세계지리",
    question: "오스트레일리아의 수도는?",
    choices: ["시드니", "멜버른", "캔버라", "퍼스"],
    answer: 2,
    explanation: "캔버라는 오스트레일리아 연방의 수도로, 시드니에서 남서쪽으로 약 240km 떨어져 있다.",
    source: { title: "Britannica, Canberra", url: "https://www.britannica.com/place/Canberra" },
  },
  {
    category: "세계지리",
    question: "나일강이 북쪽으로 흘러 마지막에 흘러드는 바다는?",
    choices: ["홍해", "지중해", "아라비아해", "흑해"],
    answer: 1,
    explanation: "나일강은 적도 남쪽에서 시작해 아프리카 북동부를 지나 지중해로 흘러든다.",
    source: { title: "Britannica, Nile River", url: "https://www.britannica.com/place/Nile-River" },
  },
  {
    category: "세계지리",
    question: "안데스산맥이 있는 대륙은?",
    choices: ["남아메리카", "아프리카", "아시아", "북아메리카"],
    answer: 0,
    explanation: "안데스산맥은 남아메리카의 산계로, 대륙 남쪽 끝에서 카리브해 연안까지 이어진다.",
    source: { title: "Britannica, Andes Mountains", url: "https://www.britannica.com/place/Andes-Mountains" },
  },
  {
    category: "세계지리",
    question: "아프리카 북부의 거의 전체를 차지하는 사막은?",
    choices: ["고비 사막", "아타카마 사막", "칼라하리 사막", "사하라 사막"],
    answer: 3,
    explanation: "사하라 사막은 아프리카 북부의 거의 전체를 차지하며, 동서 길이가 약 4,800km이다.",
    source: { title: "Britannica, Sahara", url: "https://www.britannica.com/place/Sahara-desert-Africa" },
  },
  {
    category: "세계지리",
    question: "튀르키예(터키)의 수도는?",
    choices: ["이스탄불", "앙카라", "이즈미르", "안탈리아"],
    answer: 1,
    explanation: "앙카라는 튀르키예의 수도로, 나라의 북서부에 있다.",
    source: { title: "Britannica, Ankara", url: "https://www.britannica.com/place/Ankara" },
  },
  {
    category: "세계지리",
    question: "킬리만자로산이 있는 나라는?",
    choices: ["탄자니아", "에티오피아", "우간다", "남아프리카 공화국"],
    answer: 0,
    explanation: "킬리만자로는 탄자니아 북동부, 케냐 국경 가까이에 있는 화산 산괴이다.",
    source: { title: "Britannica, Kilimanjaro", url: "https://www.britannica.com/place/Kilimanjaro" },
  },
  {
    category: "세계지리",
    question: "아마존강이 흘러드는 대양은?",
    choices: ["태평양", "인도양", "대서양", "북극해"],
    answer: 2,
    explanation: "아마존강은 페루 안데스산맥에서 시작해 브라질을 지나 대서양으로 흘러든다.",
    source: { title: "Britannica, Amazon River", url: "https://www.britannica.com/place/Amazon-River" },
  },
  {
    category: "세계지리",
    question: "에베레스트산이 국경에 걸쳐 있는 두 나라는?",
    choices: ["인도와 네팔", "인도와 파키스탄", "부탄과 중국", "네팔과 중국"],
    answer: 3,
    explanation: "에베레스트산은 네팔과 중국 티베트 자치구의 국경에 있다.",
    source: { title: "Britannica, Mount Everest", url: "https://www.britannica.com/place/Mount-Everest" },
  },
  {
    category: "세계지리",
    question: "이집트의 수에즈 운하가 잇는 두 바다는?",
    choices: ["지중해와 홍해", "지중해와 흑해", "홍해와 아라비아해", "흑해와 카스피해"],
    answer: 0,
    explanation: "수에즈 운하는 이집트의 수에즈 지협을 남북으로 가로질러 지중해와 홍해를 잇는다.",
    source: { title: "Britannica, Suez Canal", url: "https://www.britannica.com/topic/Suez-Canal" },
  },
  {
    category: "세계지리",
    question: "브라질의 공용어는?",
    choices: ["스페인어", "포르투갈어", "영어", "프랑스어"],
    answer: 1,
    explanation: "브라질에서는 포르투갈어가 주된 언어가 되었고, 오늘날에도 공용어이다.",
    source: { title: "Britannica, Brazil", url: "https://www.britannica.com/place/Brazil" },
  },

  // ===== 과학 =====
  {
    category: "과학",
    question: "녹색 식물의 광합성에서 빛에너지를 이용해 물과 이산화 탄소로부터 만들어지는 기체는?",
    choices: ["질소", "산소", "수소", "메테인"],
    answer: 1,
    explanation: "광합성은 빛에너지로 물과 이산화 탄소를 산소와 유기 화합물로 바꾸는 과정이다.",
    source: { title: "Britannica, Photosynthesis", url: "https://www.britannica.com/science/photosynthesis" },
  },
  {
    category: "과학",
    question: "1953년 DNA가 이중 나선 구조라는 것을 밝힌 두 과학자는?",
    choices: ["왓슨과 크릭", "퀴리 부부", "보어와 하이젠베르크", "러더퍼드와 채드윅"],
    answer: 0,
    explanation: "1953년 왓슨과 크릭은 프랭클린과 윌킨스의 연구에 힘입어 DNA의 이중 나선 구조를 밝혔다.",
    source: { title: "Britannica, DNA", url: "https://www.britannica.com/science/DNA" },
  },
  {
    category: "과학",
    question: "원소 기호가 Fe인 원소는?",
    choices: ["불소", "납", "철", "구리"],
    answer: 2,
    explanation: "철의 원소 기호는 Fe이며, 주기율표 8족에 속하는 금속 원소이다.",
    source: { title: "Britannica, Iron", url: "https://www.britannica.com/science/iron-chemical-element" },
  },
  {
    category: "과학",
    question: "뉴턴의 운동 제2법칙(F = ma)에서 a가 나타내는 물리량은?",
    choices: ["속도", "가속도", "거리", "시간"],
    answer: 1,
    explanation: "질량 m이 일정한 물체에 대해 제2법칙은 F = ma로 쓰며, F는 힘, a는 가속도이다.",
    source: { title: "Britannica, Newton's laws of motion", url: "https://www.britannica.com/science/Newtons-laws-of-motion" },
  },
  {
    category: "과학",
    question: "밤하늘에서 붉게 보여 '붉은 행성(Red Planet)'이라고도 불리는 태양계 행성은?",
    choices: ["금성", "목성", "수성", "화성"],
    answer: 3,
    explanation: "화성은 밤하늘에서 붉게 보이는 천체로, 붉은 행성이라고도 불린다.",
    source: { title: "Britannica, Mars", url: "https://www.britannica.com/place/Mars-planet" },
  },
  {
    category: "과학",
    question: "해수면 높이에서 순수한 물이 끓는 온도는?",
    choices: ["0°C", "80°C", "100°C", "120°C"],
    answer: 2,
    explanation: "해수면 높이에서 물은 100°C(212°F)에서 끓는다.",
    source: { title: "Britannica, Boiling point", url: "https://www.britannica.com/science/boiling-point" },
  },
  {
    category: "과학",
    question: "척추동물의 적혈구 속에서 산소를 조직으로 운반하는 단백질은?",
    choices: ["헤모글로빈", "인슐린", "케라틴", "아밀레이스"],
    answer: 0,
    explanation: "헤모글로빈은 철을 포함한 혈액 단백질로, 적혈구 안에서 산소를 조직으로 운반한다.",
    source: { title: "Britannica, Hemoglobin", url: "https://www.britannica.com/science/hemoglobin" },
  },
  {
    category: "과학",
    question: "진공에서 빛이 1초 동안 나아가는 거리는 약 얼마인가?",
    choices: ["약 340km", "약 3,000km", "약 3만km", "약 30만km"],
    answer: 3,
    explanation: "진공에서 빛의 속력은 정확히 초속 299,792,458m로 정의되어 있어, 1초에 약 30만km를 간다.",
    source: { title: "Britannica, Speed of light", url: "https://www.britannica.com/science/speed-of-light" },
  },
  {
    category: "과학",
    question: "1859년 '종의 기원'을 펴내 자신의 진화 이론을 처음 공개적으로 펼친 과학자는?",
    choices: ["멘델", "다윈", "라마르크", "뉴턴"],
    answer: 1,
    explanation: "다윈은 비글호 항해 뒤 세운 이론을 1859년 '종의 기원'에서 처음 공개적으로 펼쳤다.",
    source: { title: "Britannica, Charles Darwin", url: "https://www.britannica.com/biography/Charles-Darwin" },
  },
  {
    category: "과학",
    question: "화학식이 NaCl인 물질은?",
    choices: ["탄산 칼슘", "수산화 나트륨", "염화 칼륨", "염화 나트륨"],
    answer: 3,
    explanation: "흔히 소금이라 부르는 염화 나트륨의 화학식은 NaCl이며, 바닷물에 녹은 성분의 약 80%를 차지한다.",
    source: { title: "Britannica, Sodium", url: "https://www.britannica.com/science/sodium" },
  },

  // ===== 예술과 문화 =====
  {
    category: "예술과 문화",
    question: "지금 파리 루브르 박물관에 걸려 있는 '모나리자'를 그린 화가는?",
    choices: ["미켈란젤로", "레오나르도 다빈치", "라파엘로", "보티첼리"],
    answer: 1,
    explanation: "모나리자는 레오나르도 다빈치가 1503~1519년 사이에 그린 유화로, 루브르 박물관에 있다.",
    source: { title: "Britannica, Mona Lisa", url: "https://www.britannica.com/topic/Mona-Lisa-painting" },
  },
  {
    category: "예술과 문화",
    question: "1889년 프랑스 생레미의 요양원에 머물며 '별이 빛나는 밤'을 그린 화가는?",
    choices: ["모네", "고갱", "빈센트 반 고흐", "세잔"],
    answer: 2,
    explanation: "반 고흐는 1889년 생레미 근처 요양원에 머무는 동안 '별이 빛나는 밤'을 그렸다.",
    source: { title: "Britannica, The Starry Night", url: "https://www.britannica.com/topic/The-Starry-Night" },
  },
  {
    category: "예술과 문화",
    question: "이탈리아 베로나를 배경으로 한 희곡 '로미오와 줄리엣'의 작가는?",
    choices: ["셰익스피어", "괴테", "몰리에르", "입센"],
    answer: 0,
    explanation: "셰익스피어의 '로미오와 줄리엣'은 이탈리아 베로나를 배경으로 한다.",
    source: { title: "Britannica, Romeo and Juliet", url: "https://www.britannica.com/topic/Romeo-and-Juliet" },
  },
  {
    category: "예술과 문화",
    question: "근대 소설의 원형으로 꼽히는 '돈키호테'의 작가는?",
    choices: ["단테", "톨스토이", "빅토르 위고", "세르반테스"],
    answer: 3,
    explanation: "'돈키호테'는 미겔 데 세르반테스의 소설로, 근대 소설의 원형으로 여겨진다.",
    source: { title: "Britannica, Don Quixote", url: "https://www.britannica.com/topic/Don-Quixote-novel" },
  },
  {
    category: "예술과 문화",
    question: "1937년 스페인 바스크 지방의 도시가 폭격당한 일을 그린 '게르니카'의 화가는?",
    choices: ["살바도르 달리", "파블로 피카소", "앙리 마티스", "프란시스코 고야"],
    answer: 1,
    explanation: "'게르니카'(1937)는 독일군의 게르니카 폭격에 대한 피카소의 응답으로 그린 작품이다.",
    source: { title: "Britannica, Pablo Picasso", url: "https://www.britannica.com/biography/Pablo-Picasso" },
  },
  {
    category: "예술과 문화",
    question: "오페라 '마술피리'를 작곡한 음악가는?",
    choices: ["모차르트", "베르디", "바그너", "푸치니"],
    answer: 0,
    explanation: "'마술피리'는 모차르트의 2막 징슈필로, 독일어 대본은 시카네더가 썼다.",
    source: { title: "Britannica, The Magic Flute", url: "https://www.britannica.com/topic/The-Magic-Flute" },
  },
  {
    category: "예술과 문화",
    question: "인도 아그라에 있는 영묘 타지마할을 지은 무굴 제국의 황제는?",
    choices: ["아크바르", "바부르", "샤자한", "아우랑제브"],
    answer: 2,
    explanation: "타지마할은 무굴 황제 샤자한(재위 1628~1658)이 아그라에 지은 영묘이다.",
    source: { title: "Britannica, Taj Mahal", url: "https://www.britannica.com/topic/Taj-Mahal" },
  },
  {
    category: "예술과 문화",
    question: "한 명의 창자가 고수의 북장단에 맞추어 소리와 아니리로 이야기를 엮어 구연하는 전통 공연 예술은?",
    choices: ["시조", "민요", "탈춤", "판소리"],
    answer: 3,
    explanation: "판소리는 창자가 고수의 북장단에 맞춰 이야기를 구연하며, 2003년 유네스코 인류무형문화유산이 되었다.",
    source: { title: "한국민족문화대백과사전, 판소리", url: "https://encykorea.aks.ac.kr/Article/E0059663" },
  },
  {
    category: "예술과 문화",
    question: "'씨름', '무동' 등이 실린 조선 후기 풍속도 화첩을 그린 화가는?",
    choices: ["김홍도", "안견", "정선", "장승업"],
    answer: 0,
    explanation: "김홍도 필 풍속도 화첩은 조선 후기 화가 김홍도가 그린 풍속화 25점으로 이루어져 있다.",
    source: { title: "한국민족문화대백과사전, 김홍도 필 풍속도 화첩", url: "https://encykorea.aks.ac.kr/Article/E0013639" },
  },
  {
    category: "예술과 문화",
    question: "'춘향전'에서 춘향과 이 도령이 광한루에서 만나 사랑에 빠지는 고을은?",
    choices: ["전주", "남원", "경주", "안동"],
    answer: 1,
    explanation: "'춘향전'에서 남원 부사의 아들 이 도령과 춘향은 광한루에서 만나 사랑에 빠진다.",
    source: { title: "한국민족문화대백과사전, 춘향전", url: "https://encykorea.aks.ac.kr/Article/E0058064" },
  },
];
if (typeof module !== "undefined") module.exports = QUESTIONS;
